#!/bin/bash

#echo "Present Working Directory: $PWD"
#echo "PYTHONPATH: $PYTHONPATH"

./bash/TotalClean.sh
echo -e "\n>>>>>>> Started Creating RooWorkSpace <<<<<<<\n"
./bash/pdfCollection.sh
echo -e "\n>>>>>>> Started Running Fitting Procedure <<<<<<<\n"
./bash/seqCollection.sh
echo -e "\n>>>>>>> Started Creating Plots <<<<<<<\n"
./bash/plotCollection.sh
